config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  # READ
  get 'tasks', to: 'tasks#index'

  # CREATE
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task
  # UPDATE
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  # DELETE
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <div class="form_group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form_group">
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>
  <div class="form_group">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <div class="form_group">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Update my task</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<div>
  <% @tasks.each do |task| %>
    <% if task.completed? %>
      <p>
      <%= image_tag ("ic_check_box_24px"), width: 20 %>
      <%= link_to task.title, task_path(task.id) %>
      </p>
    <% else %>
      <p>
      <%= image_tag ("ic_check_box_outline_blank_24px"), width: 20 %>
      <%= link_to task.title, task_path(task.id) %>
      </p>
    <% end %>
  <% end %>
</div>
<%= image_tag ("ic_add_24px"), width: 20 %>
<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h2><%= @task.details %></h2>
<div>
  <% if @task.completed? %>
  <p>
    <%= image_tag ("ic_check_box_24px"), width: 20 %>
    This task is completed!
  </p>
  <% else %>
  <p>
    <%= image_tag ("ic_check_box_outline_blank_24px"), width: 20 %>
    This task is not completed yet
  </p>
  <% end %>
</div>

<div>
  <%= image_tag ("trash-simple"), width: 20 %>
  <%= link_to "Destroy this task", task_path(@task.id), method: :delete, data: {confirm: "Are you sure?"} %>
</div>

<div>
  <%= image_tag ("pencil"), width: 20 %>
  <%= link_to "Edit this task", edit_task_path(@task)  %>
</div>

<div>
  <%= image_tag ("ic_settings_backup_restore_24px"), width: 20 %>
  <%= link_to "Back to list", tasks_path %>
</div>